/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shasdeor' at '5/15/17 11:40 AM' with Gradle 2.14
 *
 * @author shasdeor, @date 5/15/17 11:40 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
